export const lowStockItems = [
  {
    id: 'SKU001',
    name: 'Fresh Milk 1L',
    category: 'Dairy',
    brand: 'Farm Fresh',
    currentStock: 15,
    minStock: 50,
    stores: ['Store 1', 'Store 3'],
    priority: 'High',
  },
  {
    id: 'SKU045',
    name: 'White Bread',
    category: 'Bakery',
    brand: 'Daily Bread',
    currentStock: 8,
    minStock: 30,
    stores: ['Store 2', 'Store 5'],
    priority: 'High',
  },
  {
    id: 'SKU123',
    name: 'Bananas 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    currentStock: 12,
    minStock: 40,
    stores: ['Store 1'],
    priority: 'Medium',
  },
  {
    id: 'SKU234',
    name: 'Chicken Breast 500g',
    category: 'Meat & Poultry',
    brand: 'Fresh Choice',
    currentStock: 5,
    minStock: 25,
    stores: ['Store 4', 'Store 6'],
    priority: 'High',
  },
  {
    id: 'SKU345',
    name: 'Olive Oil 500ml',
    category: 'Pantry',
    brand: 'Golden Harvest',
    currentStock: 3,
    minStock: 15,
    stores: ['Store 7'],
    priority: 'Medium',
  },
];

export const topMovingItems = [
  {
    id: 'SKU567',
    name: 'Fresh Milk 1L',
    category: 'Dairy',
    brand: 'Farm Fresh',
    soldThisWeek: 285,
    revenue: 14250,
    trend: 'up',
  },
  {
    id: 'SKU678',
    name: 'White Bread',
    category: 'Bakery',
    brand: 'Daily Bread',
    soldThisWeek: 198,
    revenue: 9900,
    trend: 'up',
  },
  {
    id: 'SKU789',
    name: 'Bananas 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    soldThisWeek: 156,
    revenue: 7800,
    trend: 'up',
  },
  {
    id: 'SKU890',
    name: 'Instant Noodles',
    category: 'Pantry',
    brand: 'Quick Meal',
    soldThisWeek: 134,
    revenue: 6700,
    trend: 'up',
  },
  {
    id: 'SKU901',
    name: 'Chicken Eggs 12pcs',
    category: 'Dairy',
    brand: 'Farm Fresh',
    soldThisWeek: 89,
    revenue: 8900,
    trend: 'down',
  },
];

export const stockLevelsByStore = [
  {
    store: 'Store 1',
    totalItems: 1250,
    lowStock: 18,
    outOfStock: 5,
    value: 18200,
  },
  {
    store: 'Store 2',
    totalItems: 1180,
    lowStock: 15,
    outOfStock: 3,
    value: 15800,
  },
  {
    store: 'Store 3',
    totalItems: 1320,
    lowStock: 12,
    outOfStock: 2,
    value: 22100,
  },
  {
    store: 'Store 4',
    totalItems: 1090,
    lowStock: 20,
    outOfStock: 6,
    value: 14500,
  },
  {
    store: 'Store 5',
    totalItems: 1280,
    lowStock: 14,
    outOfStock: 4,
    value: 25600,
  },
  {
    store: 'Store 6',
    totalItems: 1150,
    lowStock: 16,
    outOfStock: 3,
    value: 19300,
  },
  {
    store: 'Store 7',
    totalItems: 1200,
    lowStock: 13,
    outOfStock: 2,
    value: 19200,
  },
];

export const inventoryTurnoverData = [
  { month: 'Jan', turnover: 8.2, target: 8.0 },
  { month: 'Feb', turnover: 7.8, target: 8.0 },
  { month: 'Mar', turnover: 8.4, target: 8.2 },
  { month: 'Apr', turnover: 9.1, target: 8.2 },
  { month: 'May', turnover: 7.9, target: 8.5 },
  { month: 'Jun', turnover: 8.8, target: 8.5 },
];

export const categoryDistribution = [
  { category: 'Fresh Produce', items: 420, value: 42000 },
  { category: 'Dairy & Eggs', items: 180, value: 35000 },
  { category: 'Meat & Poultry', items: 145, value: 28000 },
  { category: 'Bakery', items: 125, value: 18500 },
  { category: 'Pantry & Dry Goods', items: 350, value: 11200 },
];

export const inventoryOverview = {
  totalSKUs: 1220,
  lowStockItems: 108,
  outOfStockItems: 25,
  totalValue: 134700,
  turnoverRate: 8.8,
};

// Store-specific detailed inventory
export const detailedInventory = [
  {
    id: 'SKU001',
    name: 'Fresh Milk 1L',
    category: 'Dairy & Eggs',
    brand: 'Farm Fresh',
    price: 50,
    stores: {
      'Store 1': { stock: 45, minStock: 50, maxStock: 100, status: 'low' },
      'Store 2': { stock: 62, minStock: 50, maxStock: 100, status: 'good' },
      'Store 3': { stock: 38, minStock: 50, maxStock: 100, status: 'low' },
      'Store 4': { stock: 28, minStock: 50, maxStock: 100, status: 'low' },
      'Store 5': { stock: 71, minStock: 50, maxStock: 100, status: 'good' },
      'Store 6': { stock: 55, minStock: 50, maxStock: 100, status: 'good' },
      'Store 7': { stock: 83, minStock: 50, maxStock: 100, status: 'good' },
    },
  },
  {
    id: 'SKU002',
    name: 'White Bread',
    category: 'Bakery',
    brand: 'Daily Bread',
    price: 25,
    stores: {
      'Store 1': { stock: 25, minStock: 30, maxStock: 60, status: 'low' },
      'Store 2': { stock: 42, minStock: 30, maxStock: 60, status: 'good' },
      'Store 3': { stock: 18, minStock: 30, maxStock: 60, status: 'low' },
      'Store 4': { stock: 35, minStock: 30, maxStock: 60, status: 'good' },
      'Store 5': { stock: 0, minStock: 30, maxStock: 60, status: 'out' },
      'Store 6': { stock: 31, minStock: 30, maxStock: 60, status: 'good' },
      'Store 7': { stock: 47, minStock: 30, maxStock: 60, status: 'good' },
    },
  },
  {
    id: 'SKU003',
    name: 'Bananas 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    price: 35,
    stores: {
      'Store 1': { stock: 89, minStock: 40, maxStock: 120, status: 'good' },
      'Store 2': { stock: 76, minStock: 40, maxStock: 120, status: 'good' },
      'Store 3': { stock: 112, minStock: 40, maxStock: 120, status: 'good' },
      'Store 4': { stock: 23, minStock: 40, maxStock: 120, status: 'low' },
      'Store 5': { stock: 94, minStock: 40, maxStock: 120, status: 'good' },
      'Store 6': { stock: 58, minStock: 40, maxStock: 120, status: 'good' },
      'Store 7': { stock: 67, minStock: 40, maxStock: 120, status: 'good' },
    },
  },
  {
    id: 'SKU004',
    name: 'Chicken Breast 500g',
    category: 'Meat & Poultry',
    brand: 'Fresh Choice',
    price: 85,
    stores: {
      'Store 1': { stock: 15, minStock: 25, maxStock: 50, status: 'low' },
      'Store 2': { stock: 31, minStock: 25, maxStock: 50, status: 'good' },
      'Store 3': { stock: 28, minStock: 25, maxStock: 50, status: 'good' },
      'Store 4': { stock: 12, minStock: 25, maxStock: 50, status: 'low' },
      'Store 5': { stock: 42, minStock: 25, maxStock: 50, status: 'good' },
      'Store 6': { stock: 0, minStock: 25, maxStock: 50, status: 'out' },
      'Store 7': { stock: 33, minStock: 25, maxStock: 50, status: 'good' },
    },
  },
  {
    id: 'SKU005',
    name: 'Rice 5kg',
    category: 'Pantry & Dry Goods',
    brand: 'Golden Grain',
    price: 120,
    stores: {
      'Store 1': { stock: 156, minStock: 80, maxStock: 200, status: 'good' },
      'Store 2': { stock: 134, minStock: 80, maxStock: 200, status: 'good' },
      'Store 3': { stock: 187, minStock: 80, maxStock: 200, status: 'good' },
      'Store 4': { stock: 98, minStock: 80, maxStock: 200, status: 'good' },
      'Store 5': {
        stock: 212,
        minStock: 80,
        maxStock: 200,
        status: 'overstocked',
      },
      'Store 6': { stock: 145, minStock: 80, maxStock: 200, status: 'good' },
      'Store 7': { stock: 178, minStock: 80, maxStock: 200, status: 'good' },
    },
  },
  {
    id: 'SKU006',
    name: 'Chicken Eggs 12pcs',
    category: 'Dairy & Eggs',
    brand: 'Farm Fresh',
    price: 45,
    stores: {
      'Store 1': { stock: 67, minStock: 60, maxStock: 120, status: 'good' },
      'Store 2': { stock: 89, minStock: 60, maxStock: 120, status: 'good' },
      'Store 3': { stock: 45, minStock: 60, maxStock: 120, status: 'low' },
      'Store 4': { stock: 78, minStock: 60, maxStock: 120, status: 'good' },
      'Store 5': { stock: 102, minStock: 60, maxStock: 120, status: 'good' },
      'Store 6': { stock: 23, minStock: 60, maxStock: 120, status: 'low' },
      'Store 7': { stock: 91, minStock: 60, maxStock: 120, status: 'good' },
    },
  },
  {
    id: 'SKU007',
    name: 'Instant Noodles',
    category: 'Pantry & Dry Goods',
    brand: 'Quick Meal',
    price: 15,
    stores: {
      'Store 1': { stock: 234, minStock: 100, maxStock: 300, status: 'good' },
      'Store 2': { stock: 187, minStock: 100, maxStock: 300, status: 'good' },
      'Store 3': { stock: 298, minStock: 100, maxStock: 300, status: 'good' },
      'Store 4': { stock: 76, minStock: 100, maxStock: 300, status: 'low' },
      'Store 5': {
        stock: 312,
        minStock: 100,
        maxStock: 300,
        status: 'overstocked',
      },
      'Store 6': { stock: 145, minStock: 100, maxStock: 300, status: 'good' },
      'Store 7': { stock: 203, minStock: 100, maxStock: 300, status: 'good' },
    },
  },
  {
    id: 'SKU008',
    name: 'Apples 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    price: 60,
    stores: {
      'Store 1': { stock: 89, minStock: 50, maxStock: 150, status: 'good' },
      'Store 2': { stock: 67, minStock: 50, maxStock: 150, status: 'good' },
      'Store 3': { stock: 123, minStock: 50, maxStock: 150, status: 'good' },
      'Store 4': { stock: 34, minStock: 50, maxStock: 150, status: 'low' },
      'Store 5': { stock: 98, minStock: 50, maxStock: 150, status: 'good' },
      'Store 6': { stock: 78, minStock: 50, maxStock: 150, status: 'good' },
      'Store 7': {
        stock: 156,
        minStock: 50,
        maxStock: 150,
        status: 'overstocked',
      },
    },
  },
];

export const stores = [
  'Store 1',
  'Store 2',
  'Store 3',
  'Store 4',
  'Store 5',
  'Store 6',
  'Store 7',
];

export const categories = [
  'Fresh Produce',
  'Dairy & Eggs',
  'Meat & Poultry',
  'Bakery',
  'Pantry & Dry Goods',
];
