export const lowStockItems = [
  {
    id: 'SKU001',
    name: 'Fresh Milk 1L',
    category: 'Dairy',
    brand: 'Farm Fresh',
    currentStock: 15,
    minStock: 50,
    stores: ['Store 1', 'Store 3'],
    priority: 'High',
  },
  {
    id: 'SKU045',
    name: 'White Bread',
    category: 'Bakery',
    brand: 'Daily Bread',
    currentStock: 8,
    minStock: 30,
    stores: ['Store 2', 'Store 5'],
    priority: 'High',
  },
  {
    id: 'SKU123',
    name: 'Bananas 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    currentStock: 12,
    minStock: 40,
    stores: ['Store 1'],
    priority: 'Medium',
  },
  {
    id: 'SKU234',
    name: 'Chicken Breast 500g',
    category: 'Meat & Poultry',
    brand: 'Fresh Choice',
    currentStock: 5,
    minStock: 25,
    stores: ['Store 4', 'Store 6'],
    priority: 'High',
  },
  {
    id: 'SKU345',
    name: 'Olive Oil 500ml',
    category: 'Pantry',
    brand: 'Golden Harvest',
    currentStock: 3,
    minStock: 15,
    stores: ['Store 7'],
    priority: 'Medium',
  },
];

export const topMovingItems = [
  {
    id: 'SKU567',
    name: 'Fresh Milk 1L',
    category: 'Dairy',
    brand: 'Farm Fresh',
    soldThisWeek: 285,
    revenue: 14250,
    trend: 'up',
  },
  {
    id: 'SKU678',
    name: 'White Bread',
    category: 'Bakery',
    brand: 'Daily Bread',
    soldThisWeek: 198,
    revenue: 9900,
    trend: 'up',
  },
  {
    id: 'SKU789',
    name: 'Bananas 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    soldThisWeek: 156,
    revenue: 7800,
    trend: 'up',
  },
  {
    id: 'SKU890',
    name: 'Instant Noodles',
    category: 'Pantry',
    brand: 'Quick Meal',
    soldThisWeek: 134,
    revenue: 6700,
    trend: 'up',
  },
  {
    id: 'SKU901',
    name: 'Chicken Eggs 12pcs',
    category: 'Dairy',
    brand: 'Farm Fresh',
    soldThisWeek: 89,
    revenue: 8900,
    trend: 'down',
  },
];

export const stockLevelsByStore = [
  {
    store: 'Store 1',
    totalItems: 1250,
    lowStock: 18,
    outOfStock: 5,
    value: 18200,
  },
  {
    store: 'Store 2',
    totalItems: 1180,
    lowStock: 15,
    outOfStock: 3,
    value: 15800,
  },
  {
    store: 'Store 3',
    totalItems: 1320,
    lowStock: 12,
    outOfStock: 2,
    value: 22100,
  },
  {
    store: 'Store 4',
    totalItems: 1090,
    lowStock: 20,
    outOfStock: 6,
    value: 14500,
  },
  {
    store: 'Store 5',
    totalItems: 1280,
    lowStock: 14,
    outOfStock: 4,
    value: 25600,
  },
  {
    store: 'Store 6',
    totalItems: 1150,
    lowStock: 16,
    outOfStock: 3,
    value: 19300,
  },
  {
    store: 'Store 7',
    totalItems: 1200,
    lowStock: 13,
    outOfStock: 2,
    value: 19200,
  },
];

export const inventoryTurnoverData = [
  { month: 'Jan', turnover: 8.2, target: 8.0 },
  { month: 'Feb', turnover: 7.8, target: 8.0 },
  { month: 'Mar', turnover: 8.4, target: 8.2 },
  { month: 'Apr', turnover: 9.1, target: 8.2 },
  { month: 'May', turnover: 7.9, target: 8.5 },
  { month: 'Jun', turnover: 8.8, target: 8.5 },
];

export const categoryDistribution = [
  { category: 'Fresh Produce', items: 420, value: 42000 },
  { category: 'Dairy & Eggs', items: 180, value: 35000 },
  { category: 'Meat & Poultry', items: 145, value: 28000 },
  { category: 'Bakery', items: 125, value: 18500 },
  { category: 'Pantry & Dry Goods', items: 350, value: 11200 },
];

export const inventoryOverview = {
  totalSKUs: 1220,
  lowStockItems: 108,
  outOfStockItems: 25,
  totalValue: 134700,
  turnoverRate: 8.8,
};

// Store-specific detailed inventory
export const detailedInventory = [
  {
    id: 'SKU001',
    name: 'Fresh Milk 1L',
    category: 'Dairy & Eggs',
    brand: 'Farm Fresh',
    price: 50,
    stores: {
      'Store 1': { stock: 45, minStock: 50, maxStock: 100, status: 'low' },
      'Store 2': { stock: 62, minStock: 50, maxStock: 100, status: 'good' },
      'Store 3': { stock: 38, minStock: 50, maxStock: 100, status: 'low' },
      'Store 4': { stock: 28, minStock: 50, maxStock: 100, status: 'low' },
      'Store 5': { stock: 71, minStock: 50, maxStock: 100, status: 'good' },
      'Store 6': { stock: 55, minStock: 50, maxStock: 100, status: 'good' },
      'Store 7': { stock: 83, minStock: 50, maxStock: 100, status: 'good' },
    },
  },
  {
    id: 'SKU002',
    name: 'White Bread',
    category: 'Bakery',
    brand: 'Daily Bread',
    price: 25,
    stores: {
      'Store 1': { stock: 25, minStock: 30, maxStock: 60, status: 'low' },
      'Store 2': { stock: 42, minStock: 30, maxStock: 60, status: 'good' },
      'Store 3': { stock: 18, minStock: 30, maxStock: 60, status: 'low' },
      'Store 4': { stock: 35, minStock: 30, maxStock: 60, status: 'good' },
      'Store 5': { stock: 0, minStock: 30, maxStock: 60, status: 'out' },
      'Store 6': { stock: 31, minStock: 30, maxStock: 60, status: 'good' },
      'Store 7': { stock: 47, minStock: 30, maxStock: 60, status: 'good' },
    },
  },
  {
    id: 'SKU003',
    name: 'Bananas 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    price: 35,
    stores: {
      'Store 1': { stock: 89, minStock: 40, maxStock: 120, status: 'good' },
      'Store 2': { stock: 76, minStock: 40, maxStock: 120, status: 'good' },
      'Store 3': { stock: 112, minStock: 40, maxStock: 120, status: 'good' },
      'Store 4': { stock: 23, minStock: 40, maxStock: 120, status: 'low' },
      'Store 5': { stock: 94, minStock: 40, maxStock: 120, status: 'good' },
      'Store 6': { stock: 58, minStock: 40, maxStock: 120, status: 'good' },
      'Store 7': { stock: 67, minStock: 40, maxStock: 120, status: 'good' },
    },
  },
  {
    id: 'SKU004',
    name: 'Chicken Breast 500g',
    category: 'Meat & Poultry',
    brand: 'Fresh Choice',
    price: 85,
    stores: {
      'Store 1': { stock: 15, minStock: 25, maxStock: 50, status: 'low' },
      'Store 2': { stock: 31, minStock: 25, maxStock: 50, status: 'good' },
      'Store 3': { stock: 28, minStock: 25, maxStock: 50, status: 'good' },
      'Store 4': { stock: 12, minStock: 25, maxStock: 50, status: 'low' },
      'Store 5': { stock: 42, minStock: 25, maxStock: 50, status: 'good' },
      'Store 6': { stock: 0, minStock: 25, maxStock: 50, status: 'out' },
      'Store 7': { stock: 33, minStock: 25, maxStock: 50, status: 'good' },
    },
  },
  {
    id: 'SKU005',
    name: 'Rice 5kg',
    category: 'Pantry & Dry Goods',
    brand: 'Golden Grain',
    price: 120,
    stores: {
      'Store 1': { stock: 156, minStock: 80, maxStock: 200, status: 'good' },
      'Store 2': { stock: 134, minStock: 80, maxStock: 200, status: 'good' },
      'Store 3': { stock: 187, minStock: 80, maxStock: 200, status: 'good' },
      'Store 4': { stock: 98, minStock: 80, maxStock: 200, status: 'good' },
      'Store 5': {
        stock: 212,
        minStock: 80,
        maxStock: 200,
        status: 'overstocked',
      },
      'Store 6': { stock: 145, minStock: 80, maxStock: 200, status: 'good' },
      'Store 7': { stock: 178, minStock: 80, maxStock: 200, status: 'good' },
    },
  },
  {
    id: 'SKU006',
    name: 'Chicken Eggs 12pcs',
    category: 'Dairy & Eggs',
    brand: 'Farm Fresh',
    price: 45,
    stores: {
      'Store 1': { stock: 67, minStock: 60, maxStock: 120, status: 'good' },
      'Store 2': { stock: 89, minStock: 60, maxStock: 120, status: 'good' },
      'Store 3': { stock: 45, minStock: 60, maxStock: 120, status: 'low' },
      'Store 4': { stock: 78, minStock: 60, maxStock: 120, status: 'good' },
      'Store 5': { stock: 102, minStock: 60, maxStock: 120, status: 'good' },
      'Store 6': { stock: 23, minStock: 60, maxStock: 120, status: 'low' },
      'Store 7': { stock: 91, minStock: 60, maxStock: 120, status: 'good' },
    },
  },
  {
    id: 'SKU007',
    name: 'Instant Noodles',
    category: 'Pantry & Dry Goods',
    brand: 'Quick Meal',
    price: 15,
    stores: {
      'Store 1': { stock: 234, minStock: 100, maxStock: 300, status: 'good' },
      'Store 2': { stock: 187, minStock: 100, maxStock: 300, status: 'good' },
      'Store 3': { stock: 298, minStock: 100, maxStock: 300, status: 'good' },
      'Store 4': { stock: 76, minStock: 100, maxStock: 300, status: 'low' },
      'Store 5': {
        stock: 312,
        minStock: 100,
        maxStock: 300,
        status: 'overstocked',
      },
      'Store 6': { stock: 145, minStock: 100, maxStock: 300, status: 'good' },
      'Store 7': { stock: 203, minStock: 100, maxStock: 300, status: 'good' },
    },
  },
  {
    id: 'SKU008',
    name: 'Apples 1kg',
    category: 'Fresh Produce',
    brand: 'Local Farm',
    price: 60,
    stores: {
      'Store 1': { stock: 89, minStock: 50, maxStock: 150, status: 'good' },
      'Store 2': { stock: 67, minStock: 50, maxStock: 150, status: 'good' },
      'Store 3': { stock: 123, minStock: 50, maxStock: 150, status: 'good' },
      'Store 4': { stock: 34, minStock: 50, maxStock: 150, status: 'low' },
      'Store 5': { stock: 98, minStock: 50, maxStock: 150, status: 'good' },
      'Store 6': { stock: 78, minStock: 50, maxStock: 150, status: 'good' },
      'Store 7': {
        stock: 156,
        minStock: 50,
        maxStock: 150,
        status: 'overstocked',
      },
    },
  },
];

export const stores = [
  'Store 1',
  'Store 2',
  'Store 3',
  'Store 4',
  'Store 5',
  'Store 6',
  'Store 7',
];

export const categories = [
  'Fresh Produce',
  'Dairy & Eggs',
  'Meat & Poultry',
  'Bakery',
  'Pantry & Dry Goods',
];

// Placement suggestions data
export const placementSuggestions = [
  {
    id: 'PS001',
    itemId: 'SKU567',
    itemName: 'Fresh Milk 1L',
    category: 'Dairy',
    currentPlacement: {
      zone: 'Refrigerated Section',
      position: 'Middle Shelf',
      duration: '14 days',
    },
    suggestedPlacement: {
      zone: 'Premium End Cap',
      position: 'Eye Level',
      duration: '7 days',
      reasoning:
        'High demand item with 285 units sold this week. Move to premium visibility to maximize sales before expiration.',
    },
    performance: {
      currentSales: 285,
      projectedIncrease: 25,
      expectedRevenue: 17812,
      confidenceScore: 92,
    },
    priority: 'High',
    urgency: 'This Week',
    storeRecommendations: ['Store 1', 'Store 3', 'Store 5'],
    aiInsights: [
      'Item has 3-day shelf life remaining',
      'High foot traffic area can increase visibility by 40%',
      'Similar items showed 25% sales increase in end caps',
    ],
  },
  {
    id: 'PS002',
    itemId: 'SKU890',
    itemName: 'Instant Noodles',
    category: 'Pantry',
    currentPlacement: {
      zone: 'Aisle 3',
      position: 'Bottom Shelf',
      duration: '30 days',
    },
    suggestedPlacement: {
      zone: 'Checkout Counter Display',
      position: 'Impulse Buy Zone',
      duration: '14 days',
      reasoning:
        'Popular convenience item. Position near checkout for impulse purchases, especially during lunch hours.',
    },
    performance: {
      currentSales: 134,
      projectedIncrease: 45,
      expectedRevenue: 9715,
      confidenceScore: 87,
    },
    priority: 'Medium',
    urgency: 'Next Week',
    storeRecommendations: ['Store 2', 'Store 4', 'Store 7'],
    aiInsights: [
      'Peak sales during 11 AM - 2 PM',
      'Checkout placement increases impulse sales by 45%',
      'Bundle opportunity with beverages',
    ],
  },
  {
    id: 'PS003',
    itemId: 'SKU123',
    itemName: 'Bananas 1kg',
    category: 'Fresh Produce',
    currentPlacement: {
      zone: 'Produce Section',
      position: 'Side Wall',
      duration: '7 days',
    },
    suggestedPlacement: {
      zone: 'Store Entrance',
      position: 'Welcome Display',
      duration: '3 days',
      reasoning:
        'Fresh produce attracts customers. Use at entrance to create fresh, healthy store impression.',
    },
    performance: {
      currentSales: 156,
      projectedIncrease: 18,
      expectedRevenue: 9204,
      confidenceScore: 78,
    },
    priority: 'Medium',
    urgency: 'Next 3 Days',
    storeRecommendations: ['Store 1', 'Store 6'],
    aiInsights: [
      'Quick turnover needed due to ripening',
      'Entrance displays increase produce sales by 18%',
      'Peak freshness for 3 more days',
    ],
  },
  {
    id: 'PS004',
    itemId: 'SKU001',
    itemName: 'Fresh Milk 1L',
    category: 'Dairy',
    currentPlacement: {
      zone: 'Back Refrigerator',
      position: 'Low Visibility',
      duration: '21 days',
    },
    suggestedPlacement: {
      zone: 'Front Refrigerator',
      position: 'Eye Level',
      duration: '5 days',
      reasoning:
        'Low stock alert (15 units). Maximize visibility to clear remaining inventory before restocking.',
    },
    performance: {
      currentSales: 15,
      projectedIncrease: 35,
      expectedRevenue: 1012,
      confidenceScore: 95,
    },
    priority: 'High',
    urgency: 'Immediate',
    storeRecommendations: ['Store 1', 'Store 3'],
    aiInsights: [
      'Critical low stock - only 15 units remaining',
      'Eye-level placement increases dairy sales by 35%',
      'Restock scheduled in 5 days',
    ],
  },
  {
    id: 'PS005',
    itemId: 'SKU678',
    itemName: 'White Bread',
    category: 'Bakery',
    currentPlacement: {
      zone: 'Bakery Corner',
      position: 'Standard Shelf',
      duration: '10 days',
    },
    suggestedPlacement: {
      zone: 'Cross-Merchandise with Spreads',
      position: 'Bundle Display',
      duration: '7 days',
      reasoning:
        'High-performing item (198 units sold). Create bundle display with jams and spreads to increase basket size.',
    },
    performance: {
      currentSales: 198,
      projectedIncrease: 22,
      expectedRevenue: 12078,
      confidenceScore: 84,
    },
    priority: 'Medium',
    urgency: 'This Week',
    storeRecommendations: ['Store 2', 'Store 5'],
    aiInsights: [
      'Strong performance indicator',
      'Cross-merchandising increases basket size by 22%',
      'Peak sales on weekend mornings',
    ],
  },
];

// Store layout zones for placement suggestions
export const storeZones = [
  {
    id: 'entrance',
    name: 'Store Entrance',
    description: 'High traffic area for first impressions',
    visibility: 'Very High',
    footTraffic: 95,
    bestFor: ['Fresh Produce', 'Seasonal Items', 'Promotions'],
  },
  {
    id: 'endcap',
    name: 'End Cap Displays',
    description: 'High-visibility promotional areas',
    visibility: 'High',
    footTraffic: 80,
    bestFor: ['Featured Items', 'High-margin Products', 'New Arrivals'],
  },
  {
    id: 'checkout',
    name: 'Checkout Counter',
    description: 'Impulse purchase zone',
    visibility: 'High',
    footTraffic: 100,
    bestFor: ['Small Items', 'Snacks', 'Convenience Products'],
  },
  {
    id: 'eyeLevel',
    name: 'Eye Level Shelves',
    description: 'Optimal visibility at customer eye level',
    visibility: 'High',
    footTraffic: 70,
    bestFor: ['Premium Products', 'Popular Brands', 'High-margin Items'],
  },
  {
    id: 'refrigerated',
    name: 'Refrigerated Section',
    description: 'Climate-controlled area for perishables',
    visibility: 'Medium',
    footTraffic: 60,
    bestFor: ['Dairy', 'Fresh Produce', 'Meat & Poultry'],
  },
  {
    id: 'aisles',
    name: 'Main Aisles',
    description: 'Standard product placement areas',
    visibility: 'Medium',
    footTraffic: 50,
    bestFor: ['Pantry Items', 'Household Goods', 'Regular Inventory'],
  },
];

// Placement performance metrics
export const placementMetrics = {
  totalSuggestions: 45,
  implementedSuggestions: 32,
  avgSalesIncrease: 28.5,
  totalRevenueIncrease: 245000,
  successRate: 89.2,
  avgImplementationTime: 2.3, // days
};
